/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include "ffi/ir_stream/Deserializer.hpp"
#include "streaming_compression/Decompressor.hpp"
#include "streaming_compression/zstd/Decompressor.hpp"
#include "velox/connectors/clp/search_lib/BaseClpCursor.h"

namespace facebook::velox::connector::clp::search_lib {

class ClpIrCursor;

class ClpVeloxIrUnitHandler {
 public:
  ClpVeloxIrUnitHandler(std::shared_ptr<ClpIrCursor> cursor)
      : cursor_(std::move(cursor)) {}

  // Destructor
  ~ClpVeloxIrUnitHandler() = default;

  // Methods implementing `IrUnitHandlerInterface`
  [[nodiscard]] auto handle_log_event(
      ::clp::ffi::KeyValuePairLogEvent log_event)
      -> ::clp::ffi::ir_stream::IRErrorCode;

  [[nodiscard]] static auto handle_utc_offset_change(
      [[maybe_unused]] ::clp::UtcOffset utc_offset_old,
      [[maybe_unused]] ::clp::UtcOffset utc_offset_new)
      -> ::clp::ffi::ir_stream::IRErrorCode {
    return ::clp::ffi::ir_stream::IRErrorCode::IRErrorCode_Success;
  }

  [[nodiscard]] static auto handle_schema_tree_node_insertion(
      [[maybe_unused]] bool is_auto_generated,
      [[maybe_unused]] ::clp::ffi::SchemaTree::NodeLocator
          schema_tree_node_locator,
      [[maybe_unused]] std::shared_ptr<::clp::ffi::SchemaTree const> const&
          schema_tree) -> ::clp::ffi::ir_stream::IRErrorCode {
    return ::clp::ffi::ir_stream::IRErrorCode::IRErrorCode_Success;
  }

  [[nodiscard]] auto handle_end_of_stream()
      -> ::clp::ffi::ir_stream::IRErrorCode {
    return ::clp::ffi::ir_stream::IRErrorCode::IRErrorCode_Success;
  }

 private:
  std::shared_ptr<ClpIrCursor> cursor_;
};

class ClpIrCursor final : public BaseClpCursor,
                          std::enable_shared_from_this<ClpIrCursor> {
 public:
  explicit ClpIrCursor(
      clp_s::InputSource inputSource,
      std::string_view splitPath,
      bool ignoreCase)
      : BaseClpCursor(inputSource, splitPath), ignoreCase_(ignoreCase) {}

  uint64_t fetchNext(
      uint64_t numRows,
      const std::shared_ptr<std::vector<uint64_t>>& filteredRowIndices)
      override;

  const std::vector<clp_s::BaseColumnReader*>& getProjectedColumns()
      const override;

  void addDeserializedLogEvent(::clp::ffi::KeyValuePairLogEvent logEvent);

  std::optional<size_t> findProjectedColumnIdxByKeyName(
      std::string_view keyName);

  void addOrderedResolvedId(
      size_t idxOfProjectedColumn,
      ::clp::ffi::SchemaTree::Node::id_t nodeId,
      bool isAutoGenerated);

 protected:
  ErrorCode loadSplit() override;

 private:
  using OrderedResolvedId =
      std::vector<std::pair<::clp::ffi::SchemaTree::Node::id_t, bool>>;
  std::shared_ptr<::clp::ReaderInterface> irReader_{nullptr};
  bool ignoreCase_;

  std::map<std::string, size_t> projectedColumnToIdx_;
  std::vector<OrderedResolvedId> orderedResolvedIds_;
  std::optional<::clp::ffi::KeyValuePairLogEvent> deserializedLogEvent_;

  std::function<ystdlib::error_handling::Result<
      void>(bool, ::clp::ffi::SchemaTree::Node::id_t, std::string_view)>
      handleProjectionResolution =
          [this](
              [[maybe_unused]] bool isAutoGenerated,
              [[maybe_unused]] ::clp::ffi::SchemaTree::Node::id_t nodeId,
              [[maybe_unused]] std::string_view keyName)
      -> ystdlib::error_handling::Result<void> {
    auto projectedColumnIdx = findProjectedColumnIdxByKeyName(keyName);
    if (projectedColumnIdx.has_value()) {
      addOrderedResolvedId(projectedColumnIdx.value(), nodeId, isAutoGenerated);
      return ::clp::ffi::ir_stream::ir_error_code_to_errc(
          ::clp::ffi::ir_stream::IRErrorCode::IRErrorCode_Success);
    }
    return ::clp::ffi::ir_stream::ir_error_code_to_errc(
        ::clp::ffi::ir_stream::IRErrorCode::IRErrorCode_Corrupted_IR);
  };
  using QueryHandlerType = ::clp::ffi::ir_stream::search::QueryHandler<
      decltype(handleProjectionResolution)>;

  std::shared_ptr<::clp::ffi::ir_stream::
                      Deserializer<ClpVeloxIrUnitHandler, QueryHandlerType>>
      irDeserializer_;

  std::optional<::clp::ffi::KeyValuePairLogEvent> const&
  getDeserializedLogEvent() const {
    return deserializedLogEvent_;
  }
  std::vector<OrderedResolvedId> const& getOrderedResolvedIds() const {
    return orderedResolvedIds_;
  }
};

} // namespace facebook::velox::connector::clp::search_lib
