/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "ClpIrCursor.h"
#include "clp_s/InputConfig.hpp"

using namespace clp_s;

namespace facebook::velox::connector::clp::search_lib {

uint64_t ClpIrCursor::fetchNext(
    uint64_t numRows,
    const std::shared_ptr<std::vector<uint64_t>>& filteredRowIndices) {
  if (ErrorCode::Success != errorCode_) {
    return 0;
  }

  if (false == currentSplitLoaded_) {
    errorCode_ = loadSplit();
    if (ErrorCode::Success != errorCode_) {
      return 0;
    }
  }

  size_t rowsFetched{0ULL};
  // while (rowsFetched < numRows && kvir_deserializer_.has_value()) {
  //   auto const
  //   result{kvir_deserializer_.value().deserialize_next_ir_unit(kvir_decompressor_)};
  //   if (result.has_error() && std::errc::no_message != result.error()) {
  //     if (ErrorCode::Success != load_next_kvir_stream()) {
  //       return rowsFetched;
  //     }
  //     continue;
  //   }
  //   if (result.value() == ::clp::ffi::ir_stream::IrUnitType::EndOfStream) {
  //     if (ErrorCode::Success != load_next_kvir_stream()) {
  //       return rowsFetched;
  //     }
  //     continue;
  //   }
  //   if (result.value() == ::clp::ffi::ir_stream::IrUnitType::LogEvent) {
  //     auto const& ir_unit_handler =
  //     kvir_deserializer_.value().get_ir_unit_handler();
  //     marshal_row(rowsFetched, column_vectors, ir_unit_handler);
  //     ++rowsFetched;
  //   }
  // }
  return rowsFetched;
}

const std::vector<clp_s::BaseColumnReader*>& ClpIrCursor::getProjectedColumns()
    const {}

ErrorCode ClpIrCursor::loadSplit() {
  auto networkAuthOption = inputSource_ == InputSource::Filesystem
      ? NetworkAuthOption{.method = AuthMethod::None}
      : NetworkAuthOption{.method = AuthMethod::S3PresignedUrlV4};

  auto irHandler{ClpVeloxIrUnitHandler{shared_from_this()}};

  auto queryHandlerResult{QueryHandlerType::create(
      handleProjectionResolution, std::move(expr_), {}, ignoreCase_)};
  if (!queryHandlerResult) {
    VLOG(2) << "Failed to create query handler for deserialization.";
    return ErrorCode::InternalError;
  }
  auto queryHandler = std::move(queryHandlerResult).value();

  auto irPath = Path{.source = inputSource_, .path = splitPath_};
  irReader_ = try_create_reader(irPath, networkAuthOption);
  if (nullptr == irReader_) {
    VLOG(2) << "Failed to open kv-ir stream \"" << splitPath_
            << "\" for reading.";
    return ErrorCode::InternalError;
  }

  auto deserializerResult = ::clp::ffi::ir_stream::make_deserializer(
      *irReader_, irHandler, std::move(queryHandler));
  if (!deserializerResult) {
    VLOG(2) << "Failed to create deserializer for deserialization.";
    return ErrorCode::InternalError;
  }
  irDeserializer_ = std::make_shared<::clp::ffi::ir_stream::Deserializer<
      ClpVeloxIrUnitHandler,
      QueryHandlerType>>(std::move(deserializerResult).value());

  return ErrorCode::Success;
}

void ClpIrCursor::addDeserializedLogEvent(
    ::clp::ffi::KeyValuePairLogEvent logEvent) {
  deserializedLogEvent_.emplace(std::move(logEvent));
}

void ClpIrCursor::addOrderedResolvedId(
    size_t idxOfProjectedColumn,
    ::clp::ffi::SchemaTree::Node::id_t nodeId,
    bool isAutoGenerated) {
  orderedResolvedIds_.at(idxOfProjectedColumn)
      .emplace_back(std::make_pair(nodeId, isAutoGenerated));
}

std::optional<size_t> ClpIrCursor::findProjectedColumnIdxByKeyName(
    std::string_view keyName) {
  auto it = projectedColumnToIdx_.find(std::string(keyName));
  if (projectedColumnToIdx_.end() != it) {
    return std::nullopt;
  }
  return it->second;
}

auto ClpVeloxIrUnitHandler::handle_log_event(
    ::clp::ffi::KeyValuePairLogEvent log_event)
    -> ::clp::ffi::ir_stream::IRErrorCode {
  cursor_->addDeserializedLogEvent(std::move(log_event));
  return ::clp::ffi::ir_stream::IRErrorCode::IRErrorCode_Success;
}

} // namespace facebook::velox::connector::clp::search_lib
