/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include "ffi/ir_stream/Deserializer.hpp"

namespace facebook::velox::connector::clp::search_lib {

namespace ir {
static std::function handleProjectionResolution =
    []([[maybe_unused]] bool isAutoGenerated,
       [[maybe_unused]] ::clp::ffi::SchemaTree::Node::id_t nodeId,
       [[maybe_unused]] std::string_view keyName)
    -> ystdlib::error_handling::Result<void> {
  return ystdlib::error_handling::success();
};
using QueryHandlerType = ::clp::ffi::ir_stream::search::QueryHandler<
    decltype(handleProjectionResolution)>;
} // namespace ir

class ClpIrQueryHandler {
 private:
  std::map<std::string, size_t> projectedColumnToIdx_;
  std::vector<std::vector<std::pair<::clp::ffi::SchemaTree::Node::id_t, bool>>>
      orderedResolvedIds_;

  std::optional<size_t> findProjectedColumnIdxByKeyName(
      std::string_view keyName);

  void addOrderedResolvedId(
      size_t idxOfProjectedColumn,
      ::clp::ffi::SchemaTree::Node::id_t nodeId,
      bool isAutoGenerated);
};

} // namespace facebook::velox::connector::clp::search_lib
