/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include "ffi/ir_stream/Deserializer.hpp"
#include "streaming_compression/Decompressor.hpp"
#include "velox/connectors/clp/search_lib/BaseClpCursor.h"
#include "velox/connectors/clp/search_lib/ir/ClpIrUnitHandler.h"

namespace facebook::velox::connector::clp::search_lib {

class ClpIrCursor final : public BaseClpCursor {
 public:
  explicit ClpIrCursor(
      clp_s::InputSource inputSource,
      std::string_view splitPath,
      bool ignoreCase)
      : BaseClpCursor(inputSource, splitPath), ignoreCase_(ignoreCase) {}

  // TODO: Need to expose an API in CLP to get the internal counter of scanned
  // log events. Currently this returns the same number of filtered rows.
  uint64_t fetchNext(uint64_t numRows) override;

  size_t getNumFilteredRows() override;

  VectorPtr createVector(
      memory::MemoryPool* pool,
      const TypePtr& vectorType,
      size_t vectorSize) override;

 protected:
  ErrorCode loadSplit() override;

 private:
  std::shared_ptr<::clp::ReaderInterface> irReader_{nullptr};
  bool ignoreCase_;
  std::function<ystdlib::error_handling::Result<
      void>(bool, ::clp::ffi::SchemaTree::Node::id_t, std::string_view)>
      handleProjectionResolution =
          [this](
              [[maybe_unused]] bool isAutoGenerated,
              [[maybe_unused]] ::clp::ffi::SchemaTree::Node::id_t nodeId,
              [[maybe_unused]] std::string_view keyName)
      -> ystdlib::error_handling::Result<void> {
    projectedColumnNameNodeIdMap_.insert({std::string(keyName), nodeId});
    return ystdlib::error_handling::success();
  };
  using QueryHandlerType = ::clp::ffi::ir_stream::search::QueryHandler<
      decltype(handleProjectionResolution)>;
  std::shared_ptr<
      ::clp::ffi::ir_stream::Deserializer<ClpIrUnitHandler, QueryHandlerType>>
      irDeserializer_;

  ystdlib::error_handling::Result<void> deserialize(uint64_t numRows) const;

  size_t readerIndex_{0};
  std::unordered_map<std::string, ::clp::ffi::SchemaTree::Node::id_t>
      projectedColumnNameNodeIdMap_;
  std::vector<
      std::pair<std::string, clp_s::search::ast::literal_type_bitmask_t>>
  splitFieldsToNamesAndTypes() const;

  VectorPtr createVectorHelper(
      memory::MemoryPool* pool,
      const TypePtr& vectorType,
      size_t vectorSize);
};

} // namespace facebook::velox::connector::clp::search_lib
