/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "velox/connectors/clp/search_lib/ir/ClpIrQueryHandler.h"

namespace facebook::velox::connector::clp::search_lib {

void ClpIrQueryHandler::addOrderedResolvedId(
    size_t idxOfProjectedColumn,
    ::clp::ffi::SchemaTree::Node::id_t nodeId,
    bool isAutoGenerated) {
  orderedResolvedIds_.at(idxOfProjectedColumn)
      .emplace_back(std::make_pair(nodeId, isAutoGenerated));
}

std::optional<size_t> ClpIrQueryHandler::findProjectedColumnIdxByKeyName(
    std::string_view keyName) {
  auto it = projectedColumnToIdx_.find(std::string(keyName));
  if (projectedColumnToIdx_.end() != it) {
    return std::nullopt;
  }
  return it->second;
}

} // namespace facebook::velox::connector::clp::search_lib
