/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include <unordered_set>

#include "clp/streaming_compression/zstd/Decompressor.hpp"
#include "ffi/ir_stream/Deserializer.hpp"
#include "velox/connectors/clp/search_lib/BaseClpCursor.h"
#include "velox/connectors/clp/search_lib/ir/ClpIrUnitHandler.h"

namespace facebook::velox::connector::clp::search_lib {

class ClpIrCursor final : public BaseClpCursor {
 public:
  explicit ClpIrCursor(
      clp_s::InputSource inputSource,
      std::string_view splitPath,
      bool ignoreCase)
      : BaseClpCursor(inputSource, splitPath), ignoreCase_(ignoreCase) {}

  ClpIrCursor(const ClpIrCursor&) = delete;
  ClpIrCursor& operator=(const ClpIrCursor&) = delete;
  ClpIrCursor(ClpIrCursor&&) = delete;
  ClpIrCursor& operator=(ClpIrCursor&&) = delete;

  uint64_t fetchNext(uint64_t numRows) override;

  size_t getNumFilteredRows() const override;

  VectorPtr createVector(
      memory::MemoryPool* pool,
      const TypePtr& vectorType,
      size_t vectorSize) override;

 protected:
  ErrorCode loadSplit() override;

 private:
  std::function<ystdlib::error_handling::Result<void>(
      bool,
      ::clp::ffi::SchemaTree::Node::id_t,
      std::pair<std::string_view, size_t>)>
      projectionResolutionCallback_ =
          [this](
              [[maybe_unused]] bool isAutoGenerated,
              [[maybe_unused]] ::clp::ffi::SchemaTree::Node::id_t nodeId,
              [[maybe_unused]] std::pair<std::string_view, size_t>
                  projected_key_and_index)
      -> ystdlib::error_handling::Result<void> {
    auto it =
        projectedColumnIdxNodeIdsMap_.find(projected_key_and_index.second);
    if (it == projectedColumnIdxNodeIdsMap_.end()) {
      projectedColumnIdxNodeIdsMap_.insert(
          {projected_key_and_index.second,
           std::vector<::clp::ffi::SchemaTree::Node::id_t>{nodeId}});
      return ystdlib::error_handling::success();
    }
    it->second.emplace_back(nodeId);
    return ystdlib::error_handling::success();
  };
  using QueryHandlerType = ::clp::ffi::ir_stream::search::QueryHandler<
      decltype(projectionResolutionCallback_)>;
  std::shared_ptr<
      std::vector<std::unique_ptr<::clp::ffi::KeyValuePairLogEvent>>>
      filteredLogEvents_{nullptr};
  bool ignoreCase_;
  std::shared_ptr<
      ::clp::ffi::ir_stream::Deserializer<ClpIrUnitHandler, QueryHandlerType>>
      irDeserializer_{nullptr};
  std::shared_ptr<::clp::ReaderInterface> irReader_{nullptr};
  std::shared_ptr<::clp::streaming_compression::zstd::Decompressor>
      irReaderZstdWrapper_{nullptr};
  std::unordered_map<size_t, std::vector<::clp::ffi::SchemaTree::Node::id_t>>
      projectedColumnIdxNodeIdsMap_;
  std::unordered_set<size_t> jsonStringColumnIndices_;
  size_t columnIndex_{0};
  size_t projectedColumnIndex_{0};

  std::vector<
      std::pair<std::string, clp_s::search::ast::literal_type_bitmask_t>>
  splitFieldsToNamesAndTypes();

  ystdlib::error_handling::Result<void> deserialize(uint64_t numRows);

  VectorPtr createVectorHelper(
      memory::MemoryPool* pool,
      const TypePtr& vectorType,
      size_t vectorSize);

  /**
   * Creates a constant vector for metadata projection if the column is found.
   * @param projectedColumn The column to create a vector for.
   * @param vectorType The type of vector to create.
   * @param vectorSize Number of rows in the vector.
   * @param pool Memory pool for vector allocation.
   * @return A constant vector filled with the metadata value.
   * @return nullptr if the column is not in metadataColumnValues_.
   */
  VectorPtr createMetadataProjectionVector(
      const Field& projectedColumn,
      const TypePtr& vectorType,
      size_t vectorSize,
      memory::MemoryPool* pool);
};

} // namespace facebook::velox::connector::clp::search_lib
