# Copyright (c) Facebook, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build Pyvelox Wheels

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'pyvelox version'
        required: false
      ref:
        description: 'git ref to build'
        required: false
      publish:
        description: 'publish to PyPI'
        required: false
        type: boolean
        default: false
  # schedule:
  #   - cron: '15 0 * * *'
  pull_request:
    paths:
      - '.github/workflows/build_pyvelox.yml'
  push:
    paths:
      - '.github/workflows/build_pyvelox.yml'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: "${{github.ref != 'refs/heads/presto-0.293-clp-connector'}}"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [8-core-ubuntu]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.ref || github.ref }}
          fetch-depth: 0
          submodules: recursive
          persist-credentials: false

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.10'

      - name: "Restore ccache"
        uses: apache/infrastructure-actions/stash/restore@3354c1565d4b0e335b78a76aedd82153a9e144d4
        id: restore-cache
        with:
          path: "ccache"
          key: ccache-wheels-${{ matrix.os }}

      - name: "Create sdist"
        if: matrix.os == '8-core-ubuntu'
        env:
          BUILD_VERSION: "${{ inputs.version }}"
        run: |
          pipx install uv
          uv build --sdist --out-dir wheelhouse

      - name: Build wheels
        uses: pypa/cibuildwheel@faf86a6ed7efa889faf6996aa23820831055001a # v2
        env:
          BUILD_VERSION: "${{ inputs.version }}"
          CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-*"
          CIBW_ENVIRONMENT_PASS_LINUX:  "BUILD_VERSION"
          CIBW_ENVIRONMENT_LINUX: "CCACHE_DIR=/host${{ github.workspace }}/ccache"
          CCACHE_DIR: "${{ github.workspace }}/ccache" 
        with:
          output-dir: wheelhouse

      - name: "Save ccache"
        uses: apache/infrastructure-actions/stash/save@3354c1565d4b0e335b78a76aedd82153a9e144d4
        with:
          path: "ccache"
          key: ccache-wheels-${{ matrix.os }}

      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: wheels-${{ matrix.os }}
          retention-days: 5
          path: |
            ./wheelhouse/*.whl
            ./wheelhouse/*.tar.gz
