name: runner-test.yaml
on:
  push:

jobs:
  test:
    runs-on: ["self-hosted", "ubuntu-22.04"]
    steps:
      - run: "touch jkl.txt"
        shell: "bash"

      - run: "pwd"
        shell: "bash"

      - run: "echo $GITHUB_WORKSPACE"
        shell: "bash"